### ISSUE TITLE
MPG123 fails to init in release build with minify enabled

### ISSUE THREAD

**Issue by waqas-shortcut** [rosuH/MPG123-Android#3]
MPG123 works fine in debug builds but crashes at `init();` in the parameterized constructor.

Any chance you have proguard rules for libmpg123?

Trying this rule does not seem to work.
```
-keepclasseswithmembernames class * { native <methods>; }
```

Any help and guidance is appreciated.
Thanks

**Comment by rosuH** [comment]
I will confirm that ASAP.

**Comment by rosuH** [comment]
@waqas-shortcut Can not reproduce this issue. Could you post your stack trace here?

**Comment by waqas-shortcut** [comment]
@rosuH Thankyou for taking a look. 
I tried it in a multi-module setup.

Adding `-keepclasseswithmembernames class * { native <methods>; }`  to the app/proguard file resolved the issue for me. 
Initially I was under the impression that it must be added to the module that had MPG123 as dependency but that did not work.

```
Fatal Exception: java.lang.UnsatisfiedLinkError
No implementation found for int g.a.a.a.l() (tried Java_g_a_a_a_l and Java_g_a_a_a_l__)
me.rosuh.libmpg123.MPG123.init (MPG123.java)
me.rosuh.libmpg123.MPG123.<init> (MPG123.java:44)
...
```

Feel free to close it.

**Comment by rosuH** [comment]
Thanks for the feedback. It seems Android included proguard-rule file in default which keeps all native methods.

I would add this into lib aar manually.
