### ISSUE TITLE
Seek operation does not accurately seek to the requested position

### ISSUE THREAD

**Issue by waqas-shortcut** [rosuH/MPG123-Android#5]
When seeking to a position (in seconds) it does not accurately play from requested position. It is always starts playing behind. The delta ranges from 300ms to 800ms.

I divide return value of seek method by the sample rate to get the seek position it actually seeked to. The difference between requested and seekedTo position is the difference.

Any ideas why does it not accurately seek to the requested position? Is it a known issue of MPG123?
Any way to achieve seek accuracy?
Maybe after seek operation find out the num of frames within the `delta time` and use `skipFrame` method until frame of the request position is reached?

**Comment by waqas-shortcut** [comment]
A better explanation: 
It always seeks to the `floor`ed position.
If I seek at 118634, it will actually start playing from 118000, seek to 119264 the actual seek would be 119000 

Does that ring any bells?

**Comment by rosuH** [comment]
@waqas-shortcut MPG123 can be `seek` with 3 modes which are `SEEK_SET`, `SEEK_CUR `, and `SEEK_END`.

- SEEK_SET: set position to (or near to) specified offset
- SEEK_CUR: change position by offset from now
- SEEK_END: set position to offset from the end

This lib set `SEEK_SET` as the default mode and can not change for now. Maybe I can support more seek mode later.

REF: https://www.mpg123.de/api/group__mpg123__seek.shtml#gabf7633e5765e35933e264f175f5fcf8c

**Comment by rosuH** [comment]
@waqas-shortcut New version has support seek with mode. Try it and welcome to give feedback at any time. 😆

**Comment by waqas-shortcut** [comment]
@rosuH Thank you.

After updating to the new version (that also has latest version of libmpg123) the seek does not seem to work. 
Earlier I was using seek by passing in the seconds (actual playback time in seconds where it should go to forward/backward) and it was working fine except that it always rounded down to closest 1000th. 
Now seeking does not work. Reading documentation that you shared says `sampleoff | offset in samples (PCM frames)`
How is it supposed to used?

What happened to the `seek(positingInSeconds)`?

**Comment by waqas-shortcut** [comment]
@rosuH 
`protected static native int seek(long handle, float offsetInSeconds);` This is what worked fine with a little in accuracy (always behind)
Is it no more provided through libmpg123? Please let me know if there is any alternative?

**Comment by rosuH** [comment]
Try to seek with mode `SEEK_CUR`:

https://github.com/rosuH/MPG123-Android/blob/17abcf2d49beafecc5abdbd22ea61740d76e7742/libmpg123/src/main/java/me/rosuh/libmpg123/MPG123.java#L80-L94


Explanation on https://github.com/rosuH/MPG123-Android/issues/5#issuecomment-907537427.

**Comment by waqas-shortcut** [comment]
Seems like `SeekMode` is not public api.
Tried in the sample app as well.

**Comment by rosuH** [comment]
@waqas-shortcut Try the `0.1.1` version. 😉

**Comment by waqas-shortcut** [comment]
Thank you for the quick fix
But the accuracy problem is still there. SEEK_CUR gives the same results as before.
Not sure how other modes can help achieve the accuracy.
