### ISSUE TITLE
Support for mpg123_timeframe

### ISSUE THREAD

**Issue by waqas-shortcut** [rosuH/MPG123-Android#8]
Supporting [timeframe](https://www.mpg123.de/api/group__mpg123__seek.shtml#gab6c3b85832ef3de29aafdb0ef790043b) to use with `seek(handle, offsetInFrames, SEEK_SET)` will probably give better seek resutls as compared to seek with mode SEEK_CUR.

Will it be possible to support that functionality?

**Comment by rosuH** [comment]
@waqas-shortcut I would check the API of libmpg123 and try to add it this weekend. 😃

**Comment by rosuH** [comment]
@waqas-shortcut Try the `0.1.2` version, it comes with `mpg123_seek_frame` and `mpg123_timeframe` methods.

Also, I've added examples here:

https://github.com/rosuH/MPG123-Android/blob/a34c360b940acdd1f2d086f9283ef71bfdf2a40a/app/src/main/java/me/rosuh/decoder/MainActivity.kt#L113-L118

Have fun 😆

**Comment by waqas-shortcut** [comment]
Thanks 👏 
I will try seeking with this 🤞

**Comment by waqas-shortcut** [comment]
Yay, timeFrame and seekFrame gives accurate seek results. 
No more extra logic on my end for skipping frames to reach exact seek position.
Thanks a bunch.

**Comment by rosuH** [comment]
I just wrapped the API, thank the mpg123 project! 😄
